---
version: "3.7"
services:
  myapp-frontend:
    build:
      context: ./frontend
    image: abdullam/mycart-frontend:2.10
    depends_on:
      - myapp-backend
    environment:
      BACKENDLB: myapp-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /var/log
  myapp-backend:
    build:
      context: ./backend
    image: abdullam/mycart-backend:2.10
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /var/log
  myapp-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: myapp-db-logvol
        target: /var/lib/mysql
volumes:
  myapp-frontend-logvol:
  myapp-backend-logvol:
  myapp-db-logvol: