---
version: "3.7"
services:
  myapp-frontend:
    build:
      context: ./frontend
    image: abdullam/myapp-frontend:1.10
    environment:
      BACKENDLB: myapp-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /var/log
  myapp-frontend-logs:
    build:
      context: ./awslogs
    image: abdullam/myapp-frontend-logs:1.10
    depends_on:
      - myapp-frontend
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /mnt/log
        read_only: true
  myapp-backend:
    build:
      context: ./backend
    image: abdullam/myapp-backend:1.10
    depends_on:
      - myapp-frontend
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /mnt/log
        read_only: true
  myapp-backend-logs:
    build:
      context: ./awslogs
    image: abdullam/myapp-backend-logs:1.10
    depends_on:
      - myapp-backend
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /mnt/log
        read_only: true
volumes:
  myapp-frontend-logvol:
  myapp-backend-logvol: